export interface SlideContent {
  title: string;
  description: string;
  bullets: string[];
  formulaBlock?: string[];
  accentColor: string; // Tailwind colors like 'jee' or 'neet' or 'physics-purple'
}

export const CHAPTER_SLIDES: Record<number, SlideContent[]> = {
  1: [
    {
      title: "Introduction to Physical Quantities",
      description: "Physics is a quantitative science. We understand the physical world by measuring various physical quantities. A physical quantity is any property of a material or phenomenon that can be measured and described numerically.",
      bullets: [
        "Every measurement has two parts: a numerical value and a unit.",
        "General equation: Q = n × u, where 'n' is the numerical magnitude and 'u' is the measurement unit.",
        "If a unit is larger, its corresponding numerical value is smaller: n₁u₁ = n₂u₂.",
        "Example: Measuring a desk's length as 1.5 meters (1.5m) or 150 centimeters (150cm)."
      ],
      accentColor: "physics-purple",
      formulaBlock: ["Quantity (Q) = Magnitude (n) × Unit (u)"]
    },
    {
      title: "Fundamental Quantities (SI Base Units)",
      description: "Fundamental quantities are physical quantities that are independent of each other and cannot be defined in terms of other quantities. The International System of Units (SI) defines 7 base quantities.",
      bullets: [
        "Mass: Measure of inertia (Unit: kilogram, kg)",
        "Length: Spatial extent (Unit: meter, m)",
        "Time: Interval duration (Unit: second, s)",
        "Temperature: Degree of hotness/coldness (Unit: kelvin, K)",
        "Electric Current: Charge flow rate (Unit: ampere, A)",
        "Luminous Intensity: Optical brightness (Unit: candela, cd)",
        "Amount of Substance: Quantity of particles (Unit: mole, mol)"
      ],
      accentColor: "physics-blue",
      formulaBlock: ["Fundamental Units are independent baseline parameters."]
    },
    {
      title: "Derived Quantities",
      description: "Derived quantities are physical quantities that are defined in terms of one or more fundamental quantities. They are generated by combining the 7 base SI units through algebraic multiplication and division.",
      bullets: [
        "Speed = Distance / Time (SI Unit: m/s)",
        "Acceleration = Velocity / Time (SI Unit: m/s²)",
        "Force = Mass × Acceleration (SI Unit: kg·m/s² or Newton, N)",
        "Work & Energy = Force × Distance (SI Unit: kg·m²/s² or Joule, J)",
        "Power = Work / Time (SI Unit: J/s or Watt, W)"
      ],
      accentColor: "neet",
      formulaBlock: ["Force (F) = m × a = [M] × [LT⁻²] = [MLT⁻²]"]
    },
    {
      title: "Dimensions and Dimensional Formula",
      description: "The dimensions of a physical quantity are the powers (exponents) to which the fundamental quantities are raised to represent that quantity. We denote base units inside square brackets: [M] for Mass, [L] for Length, [T] for Time, etc.",
      bullets: [
        "Dimensional Formula: Expresses a physical quantity in terms of fundamental symbols.",
        "Velocity: [M⁰ L¹ T⁻¹] (no mass dependency)",
        "Acceleration: [M⁰ L¹ T⁻²]",
        "Force: [M¹ L¹ T⁻²]",
        "Work / Energy: [M¹ L² T⁻²]"
      ],
      accentColor: "jee",
      formulaBlock: [
        "Dimensional Notation: [Mᵃ Lᵇ Tᶜ Iᵈ ...]",
        "Example (Work): W = Force × distance = [MLT⁻²][L] = [ML²T⁻²]"
      ]
    },
    {
      title: "Applications of Dimensional Analysis",
      description: "Dimensional analysis is a powerful tool in physics. It helps verify derivations, convert units between systems, and establish relationships between physical quantities.",
      bullets: [
        "1. Checking Homogeneity: An equation is dimensionally correct if terms on both sides have identical dimensions (e.g. s = ut + ½at²).",
        "2. Converting Units: Translating magnitudes between unit systems (e.g., SI Joules to CGS Ergs).",
        "3. Deriving Formulas: Formulating relationships by equating dimensions (e.g. time period of a simple pendulum)."
      ],
      accentColor: "physics-purple",
      formulaBlock: [
        "Principle of Homogeneity: Dimensions of L.H.S = Dimensions of R.H.S",
        "Only quantities of same dimensions can be added or subtracted."
      ]
    }
  ]
};
