import type { ChapterGenerationRequest } from "./schema";

export const unitsMeasurementsSpec: ChapterGenerationRequest = {
  globalId: 1,
  classLevel: 11,
  classOrder: 1,
  title: "Units and Measurements",
  slug: "units-measurements",

  examTracks: ["neet", "jee"],

  difficulty: "moderate",

  expectedQuestions: {
    neet: 50,
    jeeMain: 50,
    jeeAdvanced: 20,
  },

  learningObjectives: [
    "Understand physical quantities and measurement.",
    "Understand SI units and derived units.",
    "Use dimensional analysis to check physical equations.",
    "Apply error analysis and propagation of errors.",
    "Apply significant-figure rules correctly.",
    "Understand order of magnitude and estimation.",
    "Understand the working and least count of measuring instruments.",
    "Recognize common JEE and NEET traps.",
  ],

  importantTopics: [
    "Physical quantities",
    "SI units",
    "Fundamental and derived units",
    "Dimensions",
    "Dimensional analysis",
    "Errors",
    "Propagation of errors",
    "Significant figures",
    "Order of magnitude",
    "Vernier calipers",
    "Screw gauge",
    "PYQ traps",
  ],

  prerequisites: [
    "Basic algebra",
    "Powers and exponents",
    "Scientific notation",
  ],

  specialInstructions: [
    "Prioritize exam-oriented revision over textbook-style exposition.",
    "The mind map must be useful for a three-minute rapid revision.",
    "Concepts must contain practical exam recognition and common mistakes.",
    "Examples must demonstrate different reasoning patterns.",
    "Questions must be genuinely JEE/NEET level rather than elementary recall.",
    "Avoid repetitive questions.",
    "Numerical answers and dimensions must be independently checked.",
    "Use the existing PhysicsRishi content architecture.",
  ],
};
export const motion1DSpec: ChapterGenerationRequest = {
  globalId: 2,
  classLevel: 11,
  classOrder: 2,
  title: "Motion in One Dimension",
  slug: "motion-1d",

  examTracks: ["neet", "jee"],

  difficulty: "moderate",

  expectedQuestions: {
    neet: 50,
    jeeMain: 50,
    jeeAdvanced: 20,
  },

  learningObjectives: [
    "Understand position, distance, displacement, and their physical meaning.",
    "Distinguish scalar and vector descriptions of one-dimensional motion.",
    "Interpret position-time, velocity-time, and acceleration-time graphs.",
    "Calculate average speed, average velocity, and instantaneous velocity.",
    "Understand uniform and non-uniform motion.",
    "Apply the equations of uniformly accelerated motion.",
    "Solve motion problems involving changing acceleration and piecewise motion.",
    "Use graphical methods to determine displacement, velocity, and acceleration.",
    "Analyze relative motion in one dimension.",
    "Recognize common JEE Main and NEET conceptual traps.",
    "Develop higher-level reasoning for JEE Advanced motion problems.",
  ],

  importantTopics: [
    "Position and reference point",
    "Distance and displacement",
    "Speed and velocity",
    "Average speed",
    "Average velocity",
    "Instantaneous velocity",
    "Acceleration",
    "Uniform motion",
    "Uniformly accelerated motion",
    "Equations of motion",
    "Position-time graphs",
    "Velocity-time graphs",
    "Acceleration-time graphs",
    "Graphical interpretation of motion",
    "Motion with variable acceleration",
    "Piecewise motion",
    "Relative motion in one dimension",
    "Free-fall as one-dimensional accelerated motion",
    "PYQ patterns and exam traps",
  ],

  prerequisites: [
    "Basic algebra",
    "Linear equations",
    "Graphs and slopes",
    "Basic vector and scalar concepts",
    "Units and Measurements",
  ],

  specialInstructions: [
    "Use NCERT Class 11 Physics as the conceptual foundation.",
    "Align examples and questions with JEE Main and NEET patterns.",
    "Include a higher-difficulty layer suitable for JEE Advanced-style reasoning.",
    "Clearly distinguish distance from displacement and speed from velocity.",
    "Use sign conventions explicitly in one-dimensional motion.",
    "Graphs must be interpreted physically rather than treated as purely mathematical plots.",
    "Include questions involving slope and area under motion graphs.",
    "Include piecewise and multi-stage motion problems.",
    "Include conceptual traps involving zero velocity, zero acceleration, and changing direction.",
    "Treat free fall as an application of one-dimensional uniformly accelerated motion.",
    "Avoid repetitive numerical questions using the same equation of motion.",
    "Verify all numerical answers independently.",
    "Every question must have exactly one defensible correct option.",
    "Use proper LaTeX formatting for mathematical expressions.",
    "Do not use raw Unicode approximations where a mathematical expression should be typeset.",
    "Use the existing PhysicsRishi content architecture.",
  ],
};
//chapter3spec
export const motion2DSpec: ChapterGenerationRequest = {
  globalId: 3,
  classLevel: 11,
  classOrder: 3,
  title: "Motion in Two Dimensions",
  slug: "motion-2d",

  examTracks: ["neet", "jee"],

  difficulty: "moderate",

  expectedQuestions: {
    neet: 50,
    jeeMain: 50,
    jeeAdvanced: 20,
  },

  learningObjectives: [
    "Understand position, displacement, velocity, and acceleration as vector quantities in two dimensions.",
    "Resolve vectors into rectangular components and reconstruct vectors from components.",
    "Perform vector addition and subtraction using graphical and component methods.",
    "Understand relative velocity and apply it to two-dimensional motion.",
    "Analyze projectile motion and its horizontal and vertical components.",
    "Derive and apply projectile range, maximum height, and time of flight.",
    "Analyze projectile motion for different launch angles and initial conditions.",
    "Understand uniform circular motion as two-dimensional motion with changing velocity direction.",
    "Determine centripetal acceleration and understand its physical origin.",
    "Interpret motion using vector and component-based reasoning.",
    "Recognize common JEE Main and NEET conceptual traps.",
    "Develop higher-level reasoning for JEE Advanced-style two-dimensional motion problems.",
  ],

  importantTopics: [
    "Scalars and vectors",
    "Vector representation",
    "Vector addition and subtraction",
    "Resolution of vectors into components",
    "Unit vectors",
    "Position vector",
    "Displacement vector",
    "Velocity vector",
    "Acceleration vector",
    "Relative velocity",
    "Projectile motion",
    "Horizontal and vertical components of projectile motion",
    "Time of flight",
    "Maximum height",
    "Horizontal range",
    "Projectile trajectory",
    "Projectile from an elevated point",
    "Uniform circular motion",
    "Centripetal acceleration",
    "PYQ patterns and exam traps",
  ],

  prerequisites: [
    "Units and Measurements",
    "Motion in One Dimension",
    "Basic algebra",
    "Trigonometry",
    "Graphs and slopes",
  ],

  specialInstructions: [
    "Use NCERT Class 11 Physics as the conceptual foundation.",
    "Align examples and questions with JEE Main and NEET patterns.",
    "Include a higher-difficulty layer suitable for JEE Advanced-style reasoning.",
    "Clearly distinguish scalar quantities from vector quantities.",
    "Use component-based vector methods explicitly.",
    "Use consistent coordinate axes and sign conventions.",
    "Treat projectile motion as independent horizontal and vertical motions.",
    "Give projectile motion from an elevated point dedicated treatment. Explicitly use the exact phrase 'Projectile from an elevated point', define the initial height above the landing level, explain the horizontal and oblique launch cases, derive the time of flight for an elevated launch, and include at least one worked numerical example and one exam-style question specifically involving a projectile launched from an elevated point.",
    "Include relative velocity problems with meaningful two-dimensional geometry.",
    "Explain centripetal acceleration as a change in velocity direction.",
    "Include conceptual traps involving maximum height, range, velocity components, and acceleration.",
    "Avoid repetitive numerical questions based on the same projectile formula.",
    "Include graphical and vector-based reasoning wherever appropriate.",
    "Verify all numerical answers independently.",
    "Every question must have exactly one defensible correct option.",
    "Use proper LaTeX formatting for mathematical expressions.",
    "Do not use raw Unicode approximations where a mathematical expression should be typeset.",
    "Use the existing PhysicsRishi content architecture.",
  ],
};
export const lawsOfMotionSpec: ChapterGenerationRequest = {
  globalId: 4,
  classLevel: 11,
  classOrder: 4,
  title: "Laws of Motion",
  slug: "laws-of-motion",

  examTracks: ["neet", "jee"],

  difficulty: "moderate",

  expectedQuestions: {
    neet: 50,
    jeeMain: 50,
    jeeAdvanced: 20,
  },

  learningObjectives: [
    "Understand the concept of force and its vector nature.",
    "Understand Newton's first, second, and third laws of motion.",
    "Apply Newton's laws to analyze the motion of particles and systems.",
    "Construct and interpret free-body diagrams.",
    "Identify and correctly assign forces acting on a body.",
    "Understand inertial and non-inertial reference frames at the required Class 11 level.",
    "Analyze tension, normal reaction, friction, and other common contact forces.",
    "Understand static and kinetic friction and their limiting conditions.",
    "Apply friction laws to blocks on horizontal and inclined surfaces.",
    "Analyze connected-body systems using Newton's laws.",
    "Apply Newton's laws to pulley and string systems.",
    "Understand equilibrium as the condition of zero net force.",
    "Analyze motion involving multiple forces and constraints.",
    "Recognize common NEET and JEE Main conceptual traps.",
    "Develop higher-level Newton's-law reasoning suitable for JEE Advanced-style problems.",
  ],

  importantTopics: [
    "Force and its vector nature",
    "Newton's first law",
    "Inertia",
    "Newton's second law",
    "Momentum and force",
    "Newton's third law",
    "Action-reaction pairs",
    "Free-body diagrams",
    "Common forces",
    "Normal reaction",
    "Tension",
    "Friction",
    "Static friction",
    "Limiting friction",
    "Kinetic friction",
    "Coefficient of friction",
    "Angle of friction",
    "Angle of repose",
    "Motion on a rough horizontal surface",
    "Motion on a rough inclined plane",
    "Connected bodies",
    "String and pulley systems",
    "Equilibrium",
    "Multiple-force systems",
    "Inertial and non-inertial frames",
    "Pseudo force",
    "PYQ patterns and exam traps",
  ],

  prerequisites: [
    "Units and Measurements",
    "Motion in One Dimension",
    "Motion in Two Dimensions",
    "Basic vector algebra",
    "Basic trigonometry",
  ],

  specialInstructions: [
    "Use NCERT Class 11 Physics as the conceptual foundation.",
    "Align examples and questions with JEE Main and NEET patterns.",
    "Include a higher-difficulty layer suitable for JEE Advanced-style reasoning.",
    "Treat force as a vector quantity and use consistent sign conventions.",
    "Every major force must be explained physically before being used in numerical problems.",
    "Free-body diagrams must be used explicitly and correctly.",
    "Clearly distinguish action-reaction pairs from forces acting on the same body.",
    "Explain static friction as self-adjusting up to its limiting value.",
    "Clearly distinguish static friction from kinetic friction.",
    "Include horizontal-surface, inclined-plane, connected-body, and pulley problems.",
    "Include equilibrium and multiple-force situations.",
    "Include conceptual treatment of inertial and non-inertial frames and pseudo force.",
    "Avoid repetitive questions based on the same friction or pulley setup.",
    "Include conceptual traps involving normal reaction, friction direction, tension, action-reaction pairs, and pseudo force.",
    "Verify all numerical answers independently.",
    "Every question must have exactly one defensible correct option.",
    "Use proper LaTeX formatting for mathematical expressions.",
    "Do not use raw Unicode approximations where a mathematical expression should be typeset.",
    "Use the existing PhysicsRishi content architecture.",
  ],
};
